# Generated by Django 4.2.13 on 2024-06-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
