# Generated by Django 4.2.13 on 2024-06-29 11:16

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_alter_schema_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='schema',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
