# Generated by Django 4.2.13 on 2024-06-29 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0003_alter_schema_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='schema',
            managers=[
            ],
        ),
    ]
