# Generated by Django 4.2.13 on 2024-06-29 11:36

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0004_alter_schema_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='schema',
            managers=[
                ('custom', django.db.models.manager.Manager()),
            ],
        ),
    ]
